name: Rust CI
on:
  push:
    branches: [ main ]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  code_quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: cargo check
        run: cargo check --all

      - name: cargo format check
        run: cargo fmt --all --check

      - name: cargo test
        run: cargo test --all

      - name: cargo clippy check
        run: cargo clippy --all --all-targets --all-features

  test_coverage:
    name: Calculate Test Coverage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
        - uses: actions/checkout@v3

        - name: Install tarpaulin
          run: cargo install cargo-tarpaulin

        - name: Calculate code coverage
          run: cargo tarpaulin --verbose --all-features --lib --out=Xml

        - name: Upload to codecov.io
          uses: codecov/codecov-action@v3

  publish_documentation:
    name: Publish Documentation to Github IO
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Build Documentaiton
        run: cargo doc --all --no-deps

      - name: Make index.html a link to help.html
        run: cd target/doc && ln -s help.html index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/doc

      - name: Deploy Pages artifact
        id: deployment
        uses: actions/deploy-pages@v1
